name: My first workflow
on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutrepo
      uses: actions/checkout@v4
    - name: Lister les fichiers dans $GITHUB_WORKSPACE
      run: |
        ls -la $GITHUB_WORKSPACE
        pwd
        echo "la commande marche"
    - name: Generate ASCII Art
      run: cowsay -f dragon "run for you ass" >>> dragon.txt
      